---
- hosts: servers
  become: yes
  vars:
   #user: user
  tasks:

    - name: Fail if user variable is not provided or is empty
      fail:
        msg: "ERROR: 'user' variable must be provided (e.g. -e user=USERNAME)"
      when: user is not defined or user | length == 0

    - name: Generate {{ user }} password
      set_fact:
        generate_password: "{{ lookup('pipe', 'openssl rand -base64 12 | tr -dc A-Za-z0-9') }}"
        salt: "{{ lookup('pipe', 'openssl rand -hex 4') }}"

    - name: Change {{ user }} password
      user:
        name: "{{ user }}"
        update_password: always
        password: "{{ generate_password | password_hash('sha512', salt ) }}"
        password_expire: true

    - name: Create CSV File with header (overwrite if exists)
      copy:
        dest: "./passwords.csv"
        content: "Date,Hostname,IP,user,Password\n"
        mode: '0600'
        force: yes
      delegate_to: localhost
    
    - name: Save {{ user }} new password to local file
      lineinfile:
        path: "./passwords.csv"
        line: "{{ ansible_date_time.date }},{{ ansible_facts.hostname }},{{ inventory_hostname }},{{ user }},{{ generate_password }}"
        create: true
        insertafter: EOF
      delegate_to: localhost